/**
 * Generate firebase-env.js from Vercel environment variables.
 * Runs during `npm run build` on Vercel deploy.
 *
 * Set these env vars in Vercel Dashboard → Settings → Environment Variables:
 *   FIREBASE_API_KEY
 *   FIREBASE_AUTH_DOMAIN
 *   FIREBASE_PROJECT_ID
 *   FIREBASE_STORAGE_BUCKET
 *   FIREBASE_MESSAGING_SENDER_ID
 *   FIREBASE_APP_ID
 *   FIREBASE_MEASUREMENT_ID
 */

const fs = require('fs');
const path = require('path');

const envVars = {
    apiKey:            process.env.FIREBASE_API_KEY,
    authDomain:        process.env.FIREBASE_AUTH_DOMAIN,
    projectId:         process.env.FIREBASE_PROJECT_ID,
    storageBucket:     process.env.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId:             process.env.FIREBASE_APP_ID,
    measurementId:     process.env.FIREBASE_MEASUREMENT_ID,
};

// Check if all vars are present
const missing = Object.entries(envVars).filter(([, v]) => !v).map(([k]) => k);
if (missing.length > 0) {
    console.warn(`⚠  Missing env vars: ${missing.join(', ')}`);
    console.warn('   firebase-env.js will NOT be generated.');
    console.warn('   Set them in Vercel Dashboard → Settings → Environment Variables.');
    // Don't fail the build — local dev may have the file already
    process.exit(0);
}

const output = `// Auto-generated by scripts/generate-env.js — DO NOT EDIT
window.__FIREBASE_CONFIG__ = ${JSON.stringify(envVars, null, 4)};
`;

const outPath = path.join(__dirname, '..', 'public', 'js', 'firebase-env.js');
fs.writeFileSync(outPath, output, 'utf8');
console.log('✓ firebase-env.js generated successfully');
